spring:
  application:
    name: hh api

  datasource:
    url: ${DATA_BASE_URL}
    driver-class-name: ${DATA_BASE_DRIVER_CLASS_NAME}
    username: ${DATA_BASE_USER}
    password: ${DATA_BASE_PASSWORD}
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: update

  server:
    port: 8080

  logging:
    level:
      root: INFO
      org.springframework.cloud: INFO
      org.springframework.web: INFO

jwt:
  secret:
    access: ${JWT_KEY_ACCESS}
    refresh: ${JWT_KEY_REFRESH}
  lifetime:
    access: ${LIFETIME_ACCESS_TOKEN}
    refresh: ${LIFETIME_REFRESH_TOKEN}

supper_admin:
  email: ${SUPPER_ADMIN_EMAIL}
  password: ${SUPPER_ADMIN_PASSWORD}

security:
  state:
    secret: ${AES_CODE}

hh:
  client-id: ${HH_CLIENT_ID}
  client-secret: ${HH_CLIENT_SECRET}
  redirect-uri: ${HH_REDIRECT_URL}
  base_url_api: ${HH_BASE_URL_API}
  base_url: ${HH_BASE_URL}
  count_vacancies: ${HH_COUNT_VACANCIES}
  hh-User-Agent: ${HH_USER_AGENT}
  cover_letter: ${HH_COVER_LETTER}
  search_by_similar_vacancies: ${HH_SEARCH_BY_SIMILAR_VACANCIES}
  force_cover_letter: ${HH_FORCE_COVER_LETTER}
  use_aI: ${HH_USE_AI}
  keywordsToExclude: ${HH_KEYWORDS_TO_EXCLUDE}

application:
  prePrompt: ${APP_PRE_PROMPT}
  apply-interval-min: ${APP_APPLY_INTERVAL_MIN}
  apply-interval-max: ${APP_APPLY_INTERVAL_MAX}
  page-interval-min: ${APP_PAGE_INTERVAL_MIN}
  page-interval-max: ${APP_PAGE_INTERVAL_MAX}
  dry-run: ${APP_DRY_RUN}  # режим "dry-run" (без фактической отправки откликов)