package com.example.dto.superjob;

import lombok.Builder;

import java.util.List;

@Builder
public record Vacancy(
        Integer id,
        String profession,
        Integer id_client,
        Integer id_user,
        String code,
        String external_url,
        Boolean refresh_vac,
        Boolean extend_vac,
        Boolean resumesubscription_status,
        Boolean resumesubscription_keywords,
        String resumesubscription_kwc,
        Integer resumesubscription_rws,
        Integer date_pub_to,
        Integer date_archived,
        Integer date_published,
        String work,
        String compensation,
        String address,
        String candidat,
        Town town,
        TypeOfWork type_of_work,
        PlaceOfWork place_of_work,
        Education education,
        Agency agency,
        Experience experience,
        MaritalStatus maritalstatus,
        Children children,
        List<List<Language>> languages,
        List<Catalogue> catalogues,
        Boolean is_archive,
        Boolean is_storage,
        String contact,
        String email,
        String url,
        String phone,
        String fax,
        Boolean already_sent_on_vacancy,
        Boolean favorite,
        List<String> driving_licence,
        List<MetroStation> metro,
        Boolean agreement,
        Integer payment_from,
        Integer payment_to,
        String currency,
        Boolean moveable,
        Gender gender,
        Integer age_from,
        Integer age_to,
        String firm_name,
        String firm_activity,
        String client_logo,
        String link,
        Integer views_count,
        Integer resumes_all,
        Integer resumes_new,
        String moderation_order,
        Boolean canEdit,
        List<Object> extended_search_parameters,

        // has not in doc
        List<Object> phones,
        List<Object> faxes,
        Boolean contacts_hidden,
        String contact_hiding_cause,
        Boolean is_closed,
        String vacancyRichText,
        CovidRequirement covid_vaccination_requirement,
        Boolean anonymous,
        Company client,
        Boolean rejected,
        List<Object> response_info,
        Boolean highlight,
        Boolean isBlacklisted,
        Double latitude,
        Double longitude
) {
}
